import {StyleSheet} from 'react-native';

export const ListStyle = StyleSheet.create({
  container: {
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    padding: 10,
    backgroundColor: 'white',
  },
  addTitleBtn: {
    padding: 10,
    width: 150,
    backgroundColor: '#5d5bd4',
    borderRadius: 30,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  listView: {
    padding: 10,
    width: '100%',
    borderRadius: 15,
    marginBottom: 10,
    backgroundColor: '#c4cfff',
    color: 'black',
  },
  ButtomCtn: {
    padding: 10,
    borderRadius: 25,
  },
  navigationContainer: {
    backgroundColor: 'red',
  },
  paragraph: {
    padding: 16,
    fontSize: 15,
    textAlign: 'center',
  },
  drawcontainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    width: 150,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#5d5bd4',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
  },
  listheader: {
    width: '100%',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listheadergif: {
    resizeMode: 'cover',
    width: 200,
    height: 200,
  },
  dashboardtext: {display: 'flex', flexDirection: 'row'},
  currentexpensetext: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    padding: 20,
    marginBottom: 20,
    paddingLeft: 0,
    width: '100%',
  },
  flatlistcontainer: {width: '100%', height: '80%'},
  flatlistView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    paddingLeft: 3,
    alignItems: 'center',
  },
  flatlistViewImg: {
    resizeMode: 'cover',
    width: 30,
    height: 30,
  },
  flatlistViewText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
